application: busstopped
version: 6
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: busstopped.py

builtins:
- datastore_admin: on

