application: busstopped
version: 25
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /static
  static_dir: static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /cron/news
  script: cron/search_news.py
  login: admin

- url: /test.*
  login: admin
  script: lib/gaeunit.py

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
